export const GET_PRODUCT_ITEM_REQUEST = "GET_PRODUCT_ITEM_REQUEST";
export const GET_PRODUCT_ITEM_SUCCESS ="GET_PRODUCT_ITEM_SUCCESS";
 
export const DELETE_PRODUCT_ITEM_REQUEST ="DELETE_PRODUCT_ITEM_REQUEST";
export const DELETE_PRODUCT_ITEM_SUCCESS ="DELETE_PRODUCT_ITEM_SUCCESS";

export const CREATE_PRODUCT_ITEM_REQUEST = "CREATE_PRODUCT_ITEM_REQUEST";
export const CREATE_PRODUCT_ITEM_SUCCESS ="CREATE_PRODUCT_ITEM_SUCCESS";

export const EDIT_PRODUCT_ITEM_REQUEST = "EDIT_PRODUCT_ITEM_REQUEST";
export const EDIT_PRODUCT_ITEM_SUCCESS ="EDIT_PRODUCT_ITEM_SUCCESS";

export const UPDATE_PRODUCT_ITEM_REQUEST = "UPDATE_PRODUCT_ITEM_REQUEST";
export const UPDATE_PRODUCT_ITEM_SUCCESS ="UPDATE_PRODUCT_ITEM_SUCCESS";


